import { db } from '../server/db';
import { companies } from '../shared/schema';

const hundredLocalBusinesses = [
  // Indianapolis, IN (5)
  {name: "Schott Services", phone: "3175551234", city: "Indianapolis", state: "Indiana", address: "Indianapolis, IN", latitude: 39.8, longitude: -86.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bourn2Haul Junk", phone: "3175551235", city: "Indianapolis", state: "Indiana", address: "Indianapolis, IN", latitude: 39.8, longitude: -86.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Jr Junk Removal & Hauling", phone: "3175551236", city: "Indianapolis", state: "Indiana", address: "Indianapolis, IN", latitude: 39.8, longitude: -86.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Good Fellas Junk Removal Indianapolis", phone: "3175551237", city: "Indianapolis", state: "Indiana", address: "4404 W 72nd St, Indianapolis, IN 46268", latitude: 39.8, longitude: -86.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Indy Trash Guy", phone: "3175551238", city: "Indianapolis", state: "Indiana", address: "Fishers, IN", latitude: 39.8, longitude: -86.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // San Antonio, TX (6)
  {name: "Texas Strong Hauling and Junk Removal", phone: "2105551234", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Last Load Dumpster Service", phone: "2105551235", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Just Junk Solutions, LLC", phone: "2105551236", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Missions Junk Removal", phone: "2105551237", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "We Heart Junk", phone: "2105551238", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "NX Junk & Demolition", phone: "2104655991", city: "San Antonio", state: "Texas", address: "San Antonio, TX", latitude: 29.4, longitude: -98.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Dallas, TX (6)
  {name: "Alliance Rubbish Removal", phone: "2145551234", city: "Dallas", state: "Texas", address: "Dallas, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JM Junk Removers", phone: "2148885865", city: "Dallas", state: "Texas", address: "Dallas, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Dunk Your Junk", phone: "2145551235", city: "Dallas", state: "Texas", address: "Dallas, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk North DFW", phone: "9402317688", city: "Dallas", state: "Texas", address: "Dallas, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Quest", phone: "2145551236", city: "Dallas", state: "Texas", address: "McKinney, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "HaulAway Junk Removal", phone: "4694124699", city: "Dallas", state: "Texas", address: "Dallas, TX", latitude: 32.8, longitude: -96.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Houston, TX (5)
  {name: "Houston Junk Hauling LLC", phone: "7135551234", city: "Houston", state: "Texas", address: "Houston, TX", latitude: 29.8, longitude: -95.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Your Junk Our Trunk", phone: "7135551235", city: "Houston", state: "Texas", address: "Houston, TX", latitude: 29.8, longitude: -95.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Texas Junkers", phone: "7135551236", city: "Houston", state: "Texas", address: "Houston, TX", latitude: 29.8, longitude: -95.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "HustleTown Junk Removal", phone: "7135551237", city: "Houston", state: "Texas", address: "Houston, TX", latitude: 29.8, longitude: -95.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Fire Dawgs Junk Removal Houston", phone: "7138043294", city: "Houston", state: "Texas", address: "Houston, TX", latitude: 29.8, longitude: -95.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Jacksonville, FL (5)
  {name: "Jon's Junks Junk Removal", phone: "9045551234", city: "Jacksonville", state: "Florida", address: "Jacksonville, FL", latitude: 30.3, longitude: -81.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "The Mess Haul", phone: "9045551235", city: "Jacksonville", state: "Florida", address: "Jacksonville, FL", latitude: 30.3, longitude: -81.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "904 Junk Removal", phone: "9045551236", city: "Jacksonville", state: "Florida", address: "Jacksonville, FL", latitude: 30.3, longitude: -81.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "A1A Moving & Transport", phone: "9047183370", city: "Jacksonville", state: "Florida", address: "Jacksonville, FL", latitude: 30.3, longitude: -81.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Stand Up Guys Junk Removal Jacksonville", phone: "9045551237", city: "Jacksonville", state: "Florida", address: "Jacksonville, FL", latitude: 30.3, longitude: -81.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Tampa, FL (9)
  {name: "Dump My Junk LLC", phone: "8135927922", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Trash Wizard", phone: "8137332765", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk n' Stuff Removal Services", phone: "8135551234", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Hawk's Junk Removal", phone: "8135551235", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bros. Pro Hauling", phone: "8135551236", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "All Clear Junk Removal", phone: "8135885292", city: "Tampa", state: "Florida", address: "Wesley Chapel, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk-It Tampa", phone: "8135551237", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Buddy", phone: "8779105865", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "G.I. HAUL Tampa Bay", phone: "8135551238", city: "Tampa", state: "Florida", address: "Tampa, FL", latitude: 27.9, longitude: -82.5, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Orlando, FL (5)
  {name: "Junk Angel", phone: "4075551234", city: "Orlando", state: "Florida", address: "Orlando, FL", latitude: 28.5, longitude: -81.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "World of Dumpsters & Junk Removal", phone: "4075551235", city: "Orlando", state: "Florida", address: "Orlando, FL", latitude: 28.5, longitude: -81.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "G's Junk Removal", phone: "3216167331", city: "Orlando", state: "Florida", address: "Orlando, FL", latitude: 28.5, longitude: -81.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Monkey Removal", phone: "4074527039", city: "Orlando", state: "Florida", address: "Orlando, FL", latitude: 28.5, longitude: -81.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Move It Junk Removal", phone: "4075551236", city: "Orlando", state: "Florida", address: "Orlando, FL", latitude: 28.5, longitude: -81.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Memphis, TN (5)
  {name: "The Junk Llamas", phone: "9015551234", city: "Memphis", state: "Tennessee", address: "Memphis, TN", latitude: 35.1, longitude: -90.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Clean City Hauling", phone: "9015551235", city: "Memphis", state: "Tennessee", address: "Memphis, TN", latitude: 35.1, longitude: -90.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Left Overs Junk Removal", phone: "9015551236", city: "Memphis", state: "Tennessee", address: "Memphis, TN", latitude: 35.1, longitude: -90.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Brotherhood Hauling", phone: "9015551237", city: "Memphis", state: "Tennessee", address: "Memphis, TN", latitude: 35.1, longitude: -90.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Dr. Junk Memphis", phone: "9015551238", city: "Memphis", state: "Tennessee", address: "Memphis, TN", latitude: 35.1, longitude: -90.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Louisville, KY (9)
  {name: "Junky Dunky Hauling & Junk Removal", phone: "5029667405", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Right Way Hauling", phone: "5029387619", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Sgt Junk-It", phone: "5027383888", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Hillbilly Hauling Junk Removal", phone: "5025551234", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Now You See It, Now You Don't", phone: "5025551235", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "AAA Rousse Louisville", phone: "5025551236", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JUNKCO, LLC", phone: "5025551237", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bluegrass Junk Removal LLC", phone: "5025551238", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Haulaway Junk Removal Louisville", phone: "5025551239", city: "Louisville", state: "Kentucky", address: "Louisville, KY", latitude: 38.3, longitude: -85.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Milwaukee, WI (6)
  {name: "Camo Crew Junk Removal", phone: "4145551234", city: "Milwaukee", state: "Wisconsin", address: "Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Trash Transport Junk Removal", phone: "4146009221", city: "Milwaukee", state: "Wisconsin", address: "West Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "CDR Junk Removal", phone: "4145551235", city: "Milwaukee", state: "Wisconsin", address: "Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Efficient Cleaning Services", phone: "4145551236", city: "Milwaukee", state: "Wisconsin", address: "Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "GruntWorks Junk Removal", phone: "4145551237", city: "Milwaukee", state: "Wisconsin", address: "Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Smith Brothers Junk Removal", phone: "4145551238", city: "Milwaukee", state: "Wisconsin", address: "Milwaukee, WI", latitude: 43.0, longitude: -87.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Raleigh, NC (6)
  {name: "McJunk", phone: "9195551234", city: "Raleigh", state: "North Carolina", address: "Raleigh, NC", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Dump Dawgs Junk Removal", phone: "9195551235", city: "Raleigh", state: "North Carolina", address: "Raleigh, NC", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Rojas Junk Removal", phone: "9195551236", city: "Raleigh", state: "North Carolina", address: "Raleigh, NC", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Count Junkula", phone: "9195551237", city: "Raleigh", state: "North Carolina", address: "Raleigh, NC", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Garage Brothers Junk Removal", phone: "9195551238", city: "Raleigh", state: "North Carolina", address: "8821F Gulf Court, Raleigh, NC 27617", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Raleigh Junk Removal Services, LLC", phone: "9195551239", city: "Raleigh", state: "North Carolina", address: "Raleigh, NC", latitude: 35.8, longitude: -78.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Salt Lake City, UT (7)
  {name: "Jack's Junk Removal", phone: "8015551234", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Freedom Hauling", phone: "8015551235", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Deseret Junk Removal", phone: "8015551236", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Deletion", phone: "8015551237", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "On The Move Junk Removal", phone: "8015551238", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "AAA Rousse Salt Lake City", phone: "3853166055", city: "Salt Lake City", state: "Utah", address: "Salt Lake City, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Solutions Draper", phone: "8015551239", city: "Salt Lake City", state: "Utah", address: "Draper, UT", latitude: 40.8, longitude: -111.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Kansas City, MO (5)
  {name: "KC Junk Removal & Demo", phone: "9137039967", city: "Kansas City", state: "Missouri", address: "Kansas City, MO", latitude: 39.1, longitude: -94.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "GI Junk Removal Kansas City", phone: "8165551234", city: "Kansas City", state: "Missouri", address: "Kansas City, MO", latitude: 39.1, longitude: -94.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "David's Hauling", phone: "8165551235", city: "Kansas City", state: "Missouri", address: "Kansas City, MO", latitude: 39.1, longitude: -94.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Kansas City Junk Company", phone: "8165551236", city: "Kansas City", state: "Missouri", address: "Kansas City, MO", latitude: 39.1, longitude: -94.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "American Junk Collective", phone: "8165551237", city: "Kansas City", state: "Missouri", address: "Kansas City, MO", latitude: 39.1, longitude: -94.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Albuquerque, NM (6)
  {name: "Haul It All Services", phone: "5055535545", city: "Albuquerque", state: "New Mexico", address: "2270 Wyoming Blvd NE, Albuquerque, NM 87112", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "A1 Junk Removal of Albuquerque", phone: "5055551234", city: "Albuquerque", state: "New Mexico", address: "Albuquerque, NM", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Brothers LLC Albuquerque", phone: "5055551235", city: "Albuquerque", state: "New Mexico", address: "Albuquerque, NM", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Albuquerque Junk Removal & Hauling", phone: "5055551236", city: "Albuquerque", state: "New Mexico", address: "Albuquerque, NM", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JunkCo Albuquerque", phone: "5055551237", city: "Albuquerque", state: "New Mexico", address: "Albuquerque, NM", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "A1 Services & Better Call Haul", phone: "5055551238", city: "Albuquerque", state: "New Mexico", address: "Albuquerque, NM", latitude: 35.1, longitude: -106.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Tucson, AZ (8)
  {name: "Vista Clean Junk Removal", phone: "5205551234", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JB Landscaping and Junk Removal", phone: "5209554684", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Roberts Removal & Hauling", phone: "5205551235", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Speedway Junk Removal", phone: "5205551236", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Hefty Hauling AZ", phone: "5205551237", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Hero Junk Removal", phone: "5203464376", city: "Tucson", state: "Arizona", address: "2719 N Campbell Ave #103, Tucson, AZ 85719", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Bandits", phone: "5207752501", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Tucson Junk Removal Pros", phone: "5202241904", city: "Tucson", state: "Arizona", address: "Tucson, AZ", latitude: 32.2, longitude: -110.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
];

async function add100LocalBusinesses() {
  console.log(`Adding ${hundredLocalBusinesses.length} local independent junk removal businesses...`);
  
  // Insert in batches of 50
  for (let i = 0; i < hundredLocalBusinesses.length; i += 50) {
    const batch = hundredLocalBusinesses.slice(i, i + 50);
    await db.insert(companies).values(batch);
    console.log(`Inserted batch ${Math.floor(i / 50) + 1}/${Math.ceil(hundredLocalBusinesses.length / 50)}`);
  }
  
  console.log(`✅ Successfully added ${hundredLocalBusinesses.length} local independent businesses!`);
}

add100LocalBusinesses().catch(console.error);
