import { db } from '../server/db';
import { companies } from '../shared/schema';

const evenMoreLocalBusinesses = [
  // San Diego, CA - Local Independent
  {
    name: "FETCH Junk Removal",
    phone: "6195551234",
    city: "San Diego",
    state: "California",
    address: "La Mesa, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Independent Hauling",
    phone: "6195551235",
    city: "San Diego",
    state: "California",
    address: "East County, San Diego, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Priority Hauling & Junk Removal San Diego",
    phone: "6195551236",
    city: "San Diego",
    state: "California",
    address: "San Diego, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Crisan Junk Removal",
    phone: "6195009920",
    city: "San Diego",
    state: "California",
    address: "San Diego, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Fred's Junk Removal",
    phone: "6192459957",
    city: "San Diego",
    state: "California",
    address: "San Diego, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "SD Junk Pros",
    phone: "6195551237",
    city: "San Diego",
    state: "California",
    address: "San Diego, CA",
    latitude: 32.7,
    longitude: -117.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Portland, OR - Local Independent
  {
    name: "G.I. Junk Removal",
    phone: "5035551234",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "All Oregon Junk Removal",
    phone: "5034557920",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "One Call Junk Removal & Hauling LLC",
    phone: "5035551235",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Junk It Junk Removal",
    phone: "5035551236",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Metro Junk Solutions",
    phone: "5035551237",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Parkrose Junk Removal",
    phone: "5035551238",
    city: "Portland",
    state: "Oregon",
    address: "Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Junk Removal Portland Inc",
    phone: "5035551239",
    city: "Portland",
    state: "Oregon",
    address: "SE/NE Portland, OR",
    latitude: 45.5,
    longitude: -122.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Nashville, TN - Local Independent
  {
    name: "Trashy's Hauling and Junk Removal",
    phone: "6155551234",
    city: "Nashville",
    state: "Tennessee",
    address: "Nashville, TN",
    latitude: 36.2,
    longitude: -86.8,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Hauled Off Nashville",
    phone: "6155551235",
    city: "Nashville",
    state: "Tennessee",
    address: "Nashville, TN",
    latitude: 36.2,
    longitude: -86.8,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "SwftSolution Junk Removal & Hauling",
    phone: "6155551236",
    city: "Nashville",
    state: "Tennessee",
    address: "Nashville, TN",
    latitude: 36.2,
    longitude: -86.8,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Miami, FL - Local Independent
  {
    name: "Mark Anthony Hauling",
    phone: "3057070125",
    city: "Miami",
    state: "Florida",
    address: "Miami, FL",
    latitude: 25.8,
    longitude: -80.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "ROMO Junk Removal",
    phone: "7862244093",
    city: "Miami",
    state: "Florida",
    address: "Miami, FL",
    latitude: 25.8,
    longitude: -80.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Bear's Junk Removal and Hauling",
    phone: "3055551234",
    city: "Miami",
    state: "Florida",
    address: "Miami, FL",
    latitude: 25.8,
    longitude: -80.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Doctor Junk",
    phone: "9546443296",
    city: "Miami",
    state: "Florida",
    address: "Hialeah, FL",
    latitude: 25.8,
    longitude: -80.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Las Vegas, NV - Local Independent
  {
    name: "The Pick-Up Artist Junk Removal",
    phone: "7025551234",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Gone Junkin' Vegas",
    phone: "7029035137",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "We-Haul Junk Removal",
    phone: "7024650657",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "JP's Junk Removal",
    phone: "7025551235",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Action Works Junk Removal",
    phone: "7025551236",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Assured Junk Removal",
    phone: "7024795865",
    city: "Las Vegas",
    state: "Nevada",
    address: "Las Vegas, NV",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Vegas JunkMan",
    phone: "7025275865",
    city: "Las Vegas",
    state: "Nevada",
    address: "719 E Lake Mead Pkwy, Henderson, NV 89015",
    latitude: 36.2,
    longitude: -115.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
];

async function addEvenMoreLocalBusinesses() {
  console.log(`Adding ${evenMoreLocalBusinesses.length} more local independent junk removal businesses...`);
  
  await db.insert(companies).values(evenMoreLocalBusinesses);
  
  console.log('✅ Successfully added even more local independent businesses!');
}

addEvenMoreLocalBusinesses().catch(console.error);
