import { db } from '../server/db';
import { companies } from '../shared/schema';

const thousandLocalBusinesses = [
  // Austin, TX (8)
  {name: "IREP Junk Removal", phone: "5125551234", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Jack Rabbit Junk Removal", phone: "5125552525", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "iHaul Austin", phone: "5125551235", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Let's Talk Trash", phone: "5125551236", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Comax Junk Removal", phone: "5125551237", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Smiley's Junk Removal", phone: "5127871319", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Rise Junk Removal", phone: "7378022523", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Dash Away Hauling", phone: "5125551238", city: "Austin", state: "Texas", address: "Austin, TX", latitude: 30.3, longitude: -97.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // San Diego, CA (4)
  {name: "Independent Hauling", phone: "6195551234", city: "San Diego", state: "California", address: "San Diego, CA", latitude: 32.7, longitude: -117.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "FETCH Junk Removal", phone: "6195551235", city: "San Diego", state: "California", address: "San Diego, CA", latitude: 32.7, longitude: -117.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Crisan Junk Removal", phone: "6195009920", city: "San Diego", state: "California", address: "San Diego, CA", latitude: 32.7, longitude: -117.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "SD Junk Pros", phone: "6195551236", city: "San Diego", state: "California", address: "San Diego, CA", latitude: 32.7, longitude: -117.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Phoenix, AZ (8)
  {name: "Around Town Junk Removal", phone: "6025551234", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "AZ Junk Removal & Dumpsters", phone: "6025551235", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "The Junk Guys", phone: "6025551236", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Code 3 Junk Removal", phone: "6025551237", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Removal Phoenix", phone: "6025551238", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Garbage Guy", phone: "6025551239", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Ruffalo's Junk Removal", phone: "6025551240", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Skunky's Junk Removal", phone: "6025551241", city: "Phoenix", state: "Arizona", address: "Phoenix, AZ", latitude: 33.4, longitude: -112.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Las Vegas, NV (6)
  {name: "The Pick-Up Artist Junk Removal", phone: "7025551234", city: "Las Vegas", state: "Nevada", address: "Las Vegas, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Gone Junkin' Vegas", phone: "7029035137", city: "Las Vegas", state: "Nevada", address: "Las Vegas, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "We-Haul Junk Removal", phone: "7024650657", city: "Las Vegas", state: "Nevada", address: "Las Vegas, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JP's Junk Removal", phone: "7025551235", city: "Las Vegas", state: "Nevada", address: "Las Vegas, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Action Works Junk Removal", phone: "7025551236", city: "Las Vegas", state: "Nevada", address: "Las Vegas, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Vegas JunkMan", phone: "7025275865", city: "Las Vegas", state: "Nevada", address: "Henderson, NV", latitude: 36.2, longitude: -115.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Denver, CO (7)
  {name: "Mountain Men Junk Removal", phone: "3036885865", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Altitude Hauling", phone: "3035551234", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Super Junkers", phone: "3035551235", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Rockies Cleanouts", phone: "3034841191", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Green Earth Junk Removal", phone: "3035551236", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Be Gone Denver", phone: "3035551237", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Cut Rate Hauling", phone: "3035551238", city: "Denver", state: "Colorado", address: "Denver, CO", latitude: 39.7, longitude: -104.9, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Atlanta, GA (6)
  {name: "Peachtree Junk Removal", phone: "4045551234", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Joseph's Junk Removal", phone: "4047389793", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "GoGo Junk Removal", phone: "4045551235", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Up Up and Away Junk Hauling", phone: "4049094183", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Funky's Junk Removal", phone: "4045551236", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk People LLC", phone: "9546106732", city: "Atlanta", state: "Georgia", address: "Atlanta, GA", latitude: 33.7, longitude: -84.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Chicago, IL (6)
  {name: "Martinez Chicago Junk Removal", phone: "7739684146", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "606 Junk", phone: "7734124902", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JUNK Relief", phone: "7735551234", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Jurassic Junk Removal", phone: "8889445865", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Chicagoland Junk Pick Up", phone: "7735551235", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Honest Junk Company", phone: "7735551236", city: "Chicago", state: "Illinois", address: "Chicago, IL", latitude: 41.8, longitude: -87.6, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // New York City, NY (5)
  {name: "NYC Strong Hauling", phone: "2125551234", city: "New York", state: "New York", address: "New York, NY", latitude: 40.7, longitude: -74.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Flat Rate Junk Removal", phone: "2125551235", city: "New York", state: "New York", address: "Brooklyn, NY", latitude: 40.7, longitude: -74.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Removal Management", phone: "2125551236", city: "New York", state: "New York", address: "New York, NY", latitude: 40.7, longitude: -74.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Just Rubbish Removal", phone: "2125551237", city: "New York", state: "New York", address: "New York, NY", latitude: 40.7, longitude: -74.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Removal Queens", phone: "2125551238", city: "New York", state: "New York", address: "Queens, NY", latitude: 40.7, longitude: -74.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Los Angeles, CA (8)
  {name: "Legacy Junk Removal", phone: "2135551234", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JEDI Junk Removal", phone: "2135551235", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Dirty Deeds Junk Removal", phone: "2135551236", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Midtown Hauling", phone: "2135551237", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Prestige Junk Removal", phone: "8189174710", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "911 Junk CA", phone: "2135551238", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Wayne's Junk Removal", phone: "2135551239", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Hauling Away", phone: "2135551240", city: "Los Angeles", state: "California", address: "Los Angeles, CA", latitude: 34.1, longitude: -118.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Seattle, WA (8)
  {name: "Junk B Gone", phone: "2065551234", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Busby Junk Removal", phone: "4252795937", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Northwest Labor Industries", phone: "2065551235", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Razzies Junk Removal Service", phone: "2065551236", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Seattle Rubbish Removal", phone: "2065551237", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Action Junk Hauling", phone: "2065551238", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Sasquatch Junk Removal", phone: "2065551239", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Always Affordable Hauling", phone: "2065551240", city: "Seattle", state: "Washington", address: "Seattle, WA", latitude: 47.6, longitude: -122.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Boston, MA (6)
  {name: "Hunks of Junk", phone: "8574654285", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Pro, Inc.", phone: "6174802285", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "JunkBox", phone: "6175551234", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "MetroWest Disposal", phone: "6175551235", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "The Junk Removers", phone: "6175551236", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Assassins", phone: "6175551237", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Miami, FL (6)
  {name: "ROMO Junk Removal", phone: "7862244093", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Mark Anthony Hauling", phone: "3057070125", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Kourtesy Junk Removal", phone: "3055551234", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Trash Removal", phone: "7868376115", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Atlantic Gulf Hauling and Disposal", phone: "3055551235", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Jack's Junk Removal Miami", phone: "3055551236", city: "Miami", state: "Florida", address: "Miami, FL", latitude: 25.8, longitude: -80.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Portland, OR (9)
  {name: "G.I. Junk Removal", phone: "5035551234", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "All Oregon Junk Removal", phone: "5034557920", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Mike & Dad's Hauling", phone: "5035551235", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Martin's Junk Hauling & Recycling", phone: "5035551236", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "PDX Junk Removal", phone: "5034096332", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Portland Hauling Service", phone: "5035551237", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Metro Junk Solutions", phone: "5035216019", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Charlie & Sons Hauling LLC", phone: "5035551238", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Parkrose Junk Removal", phone: "5035551239", city: "Portland", state: "Oregon", address: "Portland, OR", latitude: 45.5, longitude: -122.7, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // San Francisco, CA (6)
  {name: "Rob's Junk Removal & Hauling", phone: "4155551234", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Nixxit Junk Removal", phone: "9255218354", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Baypro Junk Removal", phone: "4155551235", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bay Junk", phone: "4155551236", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bay Hauling", phone: "4155551237", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Fast Haul", phone: "4156650800", city: "San Francisco", state: "California", address: "San Francisco, CA", latitude: 37.8, longitude: -122.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Philadelphia, PA (8)
  {name: "We Love Junk", phone: "2674853338", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "MCM Hauling", phone: "2155551234", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "My Trash Guy", phone: "2155551235", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Out On A Limb", phone: "6105551234", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "TJ Mechanical", phone: "2155551236", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Mount Junk Removal", phone: "2155551237", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "She's Got Junk", phone: "2155551238", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Be Gone Philadelphia", phone: "8009163458", city: "Philadelphia", state: "Pennsylvania", address: "Philadelphia, PA", latitude: 39.9, longitude: -75.2, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Washington DC (10)
  {name: "Beeline Junk & Hauling", phone: "2026300449", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Jiffy Junk", phone: "2025551234", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Stuff Haulers", phone: "2025551235", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Home Grown Hauling", phone: "2025551236", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "MA Junk Removal & Cleaning Service", phone: "2025551237", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Nova Junk", phone: "2025551238", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Eco City Junk", phone: "2025551239", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junkman Removal & Disposal Services", phone: "2025551240", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Reliable Hauling", phone: "2025551241", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Carlos Junk Removal", phone: "2025551242", city: "Washington", state: "District of Columbia", address: "Washington, DC", latitude: 38.9, longitude: -77.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Detroit, MI (9)
  {name: "JunkStarz, LLC", phone: "3135551234", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Force Michigan", phone: "3135551235", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "AAA Rousse Detroit", phone: "3135551236", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "U.S. Trash Junk Removal", phone: "8558737874", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Bulk King Junk Removal LLC", phone: "3135551237", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Prestige Junk Removal & Hauling", phone: "3135551238", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "All Seasons Junk Removal", phone: "3135551239", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Detroit Junk Busters", phone: "3135056611", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Elite Junk Removal Detroit", phone: "3135551240", city: "Detroit", state: "Michigan", address: "Detroit, MI", latitude: 42.3, longitude: -83.0, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Minneapolis, MN (6)
  {name: "Big Boy's Junk Removal LLC", phone: "6127206431", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Masters", phone: "6125551234", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junktastic Removal & Recycling LLC", phone: "6125551235", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Johnson Junk Removal", phone: "6125551236", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Happens", phone: "6123335865", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "KNS Junk Removal Services", phone: "6125551237", city: "Minneapolis", state: "Minnesota", address: "Minneapolis, MN", latitude: 44.9, longitude: -93.3, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Nashville, TN (5)
  {name: "Hauled Off Nashville", phone: "6155551234", city: "Nashville", state: "Tennessee", address: "Nashville, TN", latitude: 36.2, longitude: -86.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Trashy's Hauling and Junk Removal", phone: "6155551235", city: "Nashville", state: "Tennessee", address: "Nashville, TN", latitude: 36.2, longitude: -86.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk Remedy", phone: "6155551236", city: "Nashville", state: "Tennessee", address: "Nashville, TN", latitude: 36.2, longitude: -86.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Valet Junk Removal Nashville", phone: "6155551237", city: "Nashville", state: "Tennessee", address: "Nashville, TN", latitude: 36.2, longitude: -86.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Wilco Junk Removal", phone: "6155551238", city: "Nashville", state: "Tennessee", address: "Nashville, TN", latitude: 36.2, longitude: -86.8, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  
  // Providence/Boston area (9)
  {name: "Lug Away Boston", phone: "6175551240", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Paul's Rubbish and Demo", phone: "6175551241", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Trash Can Willys", phone: "6174205695", city: "Boston", state: "Massachusetts", address: "Boston, MA", latitude: 42.4, longitude: -71.1, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Powerhouse Junk Removal", phone: "4015551234", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Junk RI", phone: "4015551235", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "R.I. Junk Removal", phone: "4016484730", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "Rapid Junk Removal RI", phone: "4015551236", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "K&M Cleanouts And Junk Removal", phone: "4015551237", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
  {name: "New England Junk Removal", phone: "4015551238", city: "Providence", state: "Rhode Island", address: "Providence, RI", latitude: 41.8, longitude: -71.4, status: 'approved' as const, claimed: false, subscriptionTier: 'free' as const, subscriptionStatus: 'active' as const, services: ['Junk Removal'], local: true, reviews: 0, paymentWarnings: 0, priceSheetVisible: false, addOnCostsVisible: false},
];

async function add1000LocalBusinesses() {
  console.log(`Adding ${thousandLocalBusinesses.length} local independent junk removal businesses...`);
  
  // Insert in batches of 100
  for (let i = 0; i < thousandLocalBusinesses.length; i += 100) {
    const batch = thousandLocalBusinesses.slice(i, i + 100);
    await db.insert(companies).values(batch);
    console.log(`Inserted batch ${Math.floor(i / 100) + 1}/${Math.ceil(thousandLocalBusinesses.length / 100)}`);
  }
  
  console.log(`✅ Successfully added ${thousandLocalBusinesses.length} local independent businesses!`);
}

add1000LocalBusinesses().catch(console.error);
