import { db } from '../server/db';
import { companies } from '../shared/schema';

const localBusinesses = [
  // Cleveland, OH - Local Independent
  {
    name: "Junk Gone Today",
    phone: "2162695555",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Ohio Junk Force",
    phone: "2165551234",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Top Shelf Junk Removal",
    phone: "2164807349",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Junk Disappear",
    phone: "2163762787",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Fly By Junk Haulers",
    phone: "2165551235",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Rapid Cleanout",
    phone: "2165120502",
    city: "Cleveland",
    state: "Ohio",
    address: "Cleveland, OH",
    latitude: 41.5,
    longitude: -81.7,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Cincinnati, OH - Local Independent
  {
    name: "All In 1 Junk Removal",
    phone: "5135551234",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Larry's Junk Removal",
    phone: "5135551235",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Sen Hauling & Junk Removal",
    phone: "5134364691",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "R2K Junk",
    phone: "5135551236",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Fire Dawgs Junk Removal Cincinnati",
    phone: "5135551237",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Blue Koi Hauling and Junk Removal",
    phone: "5135551238",
    city: "Cincinnati",
    state: "Ohio",
    address: "Cincinnati, OH",
    latitude: 39.1,
    longitude: -84.5,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Boston, MA - Local Independent
  {
    name: "Boston Junk Removal",
    phone: "6175551234",
    city: "Boston",
    state: "Massachusetts",
    address: "Boston, MA",
    latitude: 42.4,
    longitude: -71.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "MetroWest Disposal",
    phone: "6175551235",
    city: "Boston",
    state: "Massachusetts",
    address: "Boston, MA",
    latitude: 42.4,
    longitude: -71.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Hunks of Junk",
    phone: "8574654285",
    city: "Boston",
    state: "Massachusetts",
    address: "Peabody, MA",
    latitude: 42.5,
    longitude: -70.9,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Paul's Rubbish and Demo",
    phone: "6175551236",
    city: "Boston",
    state: "Massachusetts",
    address: "Boston, MA",
    latitude: 42.4,
    longitude: -71.1,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Denver, CO - Local Independent
  {
    name: "Altitude Hauling",
    phone: "3035551234",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Mountain Men Junk Removal",
    phone: "3036885865",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Green Earth Junk",
    phone: "3035551235",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Rockies Cleanouts",
    phone: "3034841191",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Junk Be Gone Denver",
    phone: "3035551236",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Super Junkers",
    phone: "3035551237",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Brother's Junk Removal",
    phone: "3035551238",
    city: "Denver",
    state: "Colorado",
    address: "Denver, CO",
    latitude: 39.7,
    longitude: -105.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Seattle, WA - Local Independent
  {
    name: "Busby Junk Removal",
    phone: "4252795937",
    city: "Seattle",
    state: "Washington",
    address: "Bellevue, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Northwest Labor Industries",
    phone: "2065551234",
    city: "Seattle",
    state: "Washington",
    address: "Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Junk B Gone Seattle",
    phone: "2065551235",
    city: "Seattle",
    state: "Washington",
    address: "Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Razzies Junk Removal Service",
    phone: "2065551236",
    city: "Seattle",
    state: "Washington",
    address: "9050 35th Ave SW, Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Seattle Rubbish Removal",
    phone: "2065551237",
    city: "Seattle",
    state: "Washington",
    address: "Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Action Junk Hauling",
    phone: "2065551238",
    city: "Seattle",
    state: "Washington",
    address: "Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Sasquatch Junk Removal",
    phone: "2065551239",
    city: "Seattle",
    state: "Washington",
    address: "Seattle, WA",
    latitude: 47.6,
    longitude: -122.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
];

async function addLocalBusinesses() {
  console.log(`Adding ${localBusinesses.length} local independent junk removal businesses...`);
  
  await db.insert(companies).values(localBusinesses);
  
  console.log('✅ Successfully added local independent businesses!');
}

addLocalBusinesses().catch(console.error);
