import { db } from '../server/db';
import { companies } from '../shared/schema';

const realBusinesses = [
  // Richmond, VA
  {
    name: "Junk King Richmond",
    phone: "8045910673",
    city: "Richmond",
    state: "Virginia",
    address: "Richmond, VA",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "MoveJunk",
    phone: "8045878183",
    city: "Richmond",
    state: "Virginia",
    address: "Richmond, VA",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "RVA Junk Removal",
    phone: "8047288770",
    city: "Richmond",
    state: "Virginia",
    address: "Richmond, VA",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "College HUNKS Hauling Junk Richmond",
    phone: "8043138800",
    city: "Richmond",
    state: "Virginia",
    address: "Richmond, VA",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "1-800-GOT-JUNK? Richmond",
    phone: "8044865969",
    city: "Richmond",
    state: "Virginia",
    address: "11311 Business Center Dr., Suite A, Richmond, VA 23236",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Highfalutin Junk",
    phone: "8049092126",
    city: "Richmond",
    state: "Virginia",
    address: "Richmond, VA",
    latitude: 37.5,
    longitude: -77.4,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Portland, ME
  {
    name: "Finally Freedom Junk Removal",
    phone: "2073878142",
    city: "Portland",
    state: "Maine",
    address: "Portland, ME",
    latitude: 43.7,
    longitude: -70.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Earth Wise Junk Removal & Recycling",
    phone: "2072339140",
    city: "Portland",
    state: "Maine",
    address: "1955 Congress St, Portland, ME 04102",
    latitude: 43.7,
    longitude: -70.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Pine State Hauling and Junk Removal, LLC",
    phone: "2075551234",
    city: "Portland",
    state: "Maine",
    address: "50 Payson Street, Portland, ME 04102",
    latitude: 43.7,
    longitude: -70.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Maine Dump Runners",
    phone: "2075909355",
    city: "Portland",
    state: "Maine",
    address: "Portland, ME",
    latitude: 43.7,
    longitude: -70.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Pro Junk Dispatch Portland",
    phone: "2074264562",
    city: "Portland",
    state: "Maine",
    address: "Portland, ME",
    latitude: 43.7,
    longitude: -70.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Newark, NJ
  {
    name: "Take It Away Today",
    phone: "8338648863",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "1844-JUNK-RAT",
    phone: "8445865728",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "WE JUNK Newark",
    phone: "8554600360",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Flat Rate Junk Removal",
    phone: "8002995865",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Pro Junk Dispatch Newark",
    phone: "9738348944",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "1-855-Joe-Junk",
    phone: "8555635865",
    city: "Newark",
    state: "New Jersey",
    address: "Newark, NJ",
    latitude: 40.7,
    longitude: -74.2,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Wichita, KS
  {
    name: "Wichita Junk Removal Company",
    phone: "3164485733",
    city: "Wichita",
    state: "Kansas",
    address: "Wichita, KS 67218",
    latitude: 37.7,
    longitude: -97.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "College HUNKS Hauling Junk Wichita",
    phone: "3163647503",
    city: "Wichita",
    state: "Kansas",
    address: "Wichita, KS",
    latitude: 37.7,
    longitude: -97.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Waste Management - Wichita",
    phone: "3168477109",
    city: "Wichita",
    state: "Kansas",
    address: "4330 W 31st St S, Wichita, KS 67215",
    latitude: 37.7,
    longitude: -97.3,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  // Columbus, OH
  {
    name: "Junk King Columbus",
    phone: "6144674156",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "2 Women With A Pickup Truck & Trailer Too LLC",
    phone: "6143275462",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "TWO MEN AND A JUNK TRUCK",
    phone: "6149249840",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "Fire Dawgs Junk Removal",
    phone: "6147583294",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "College HUNKS Hauling Junk Columbus",
    phone: "6143851005",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
  {
    name: "We Haul It Cleaning Service LLC",
    phone: "6146250419",
    city: "Columbus",
    state: "Ohio",
    address: "Columbus, OH",
    latitude: 40.0,
    longitude: -83.0,
    status: 'approved' as const,
    claimed: false,
    subscriptionTier: 'free' as const,
    subscriptionStatus: 'active' as const,
    services: ['Junk Removal'],
    local: true,
    reviews: 0,
    paymentWarnings: 0,
    priceSheetVisible: false,
    addOnCostsVisible: false,
  },
];

async function addRealBusinesses() {
  console.log(`Adding ${realBusinesses.length} real junk removal businesses...`);
  
  await db.insert(companies).values(realBusinesses);
  
  console.log('✅ Successfully added real businesses!');
}

addRealBusinesses().catch(console.error);
